.TH neorc 8
.SH NAME
neorc \- neoinit run control

.SH SYNOPSIS
.B neorc
[\fIOPTIONS\fR] \fISERVICE\fR...

.SH DESCRIPTION
.B neorc
is the management interface to \fBneoinit\fR.
.I SERVICE
is a directory name relative to /etc/neorc
(can also include /etc/neorc/ in the service name).
.SH OPTIONS
If no option is given,
.B neorc
will just print a small diagnostic message to stdout, saying if the service
is up, down, finished or failed, and for how long it has been in that state.
.TP 5
.B \-o
Once.
If the service is not running, start it.
If it stops, do not restart it.
.TP
.B \-u
Up.
If the service is not running, start it.
If it stops, restart it.
.TP
.B \-d
Down.
If the service is running, send it a TERM signal and then a CONT signal.
After it stops, do not restart it.
.TP
.B \-R
Enable respawn.
Set respawn option.
This does not start/stop the service.
.TP
.B \-r
Disable respawn.
Unset respawn option.
This does not start/stop the service.
.TP
.B \-t
Terminate.
Send the service a TERM signal.
.TP
.B \-k
Kill.
Send the service a KILL signal.
.TP
.B \-g
Get PID.
Just print the PID of the service if it is running.
.TP
.B \-C
Clear.
If the service is finished, reset its state.
This is useful if a dependency of a service should be started again
together with that service.
.TP
.B \-P \fIpid\fR
Set PID.
Tell neoinit the PID of the service.
This is useful for services that fork themselves in the background with
a new PID to supervise.
.TP
.B \-D
Print dependencies.
This will print the names of all the services that were started because
this services depended on them.
Please note that this is not done recursively, only direct dependencies
are listed.
.TP
.B \-H
Print history.
This will print the names of the last spawned processes.
This can be helpful if you see a process looping
(initialization fails and it is restarting all the time).

.SH "EXIT STATUS"
Generally,
.B neorc
returns 0 if everything is ok or 1 if an error has occurred (could not
open /etc/neorc/in or /etc/neorc/out or there is no service with the
given name).

.SH AUTHOR
.B neorc
is based on
.B msvc
written by Felix von Leitner.
.I http://www.fefe.de/minit/

.SH "SEE ALSO"
neoinit(8)
